Web/FinalPoint.Web/Controllers/AddDisposeController.cs
// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace FinalPoint.Web.Controllers
{
    using System.Security.Claims;
    using System.Threading.Tasks;

    using AutoMapper;
    using FinalPoint.Data.Models;
    using FinalPoint.Data.Models.Enums;
    using FinalPoint.Web.Business.Interfaces;
    using FinalPoint.Web.ViewModels;
    using FinalPoint.Web.ViewModels.AddDispose;
    using FinalPoint.Web.ViewModels.DTOs;
    using FinalPoint.Web.ViewModels.DTOs.AddDisposeParcel;
    using Microsoft.AspNetCore.Identity;
    using Microsoft.AspNetCore.Mvc;

    public class AddDisposeController : BaseController
    {
        private readonly IOfficeService officeService;
        private readonly IClientService clientService;
        private readonly IParcelService parcelService;
        private readonly IUserService userService;
        private readonly IEmailService mailService;
        private readonly UserManager<ApplicationUser> userManager;
        private readonly IMapper mapper;

        public AddDisposeController(
            IOfficeService officeService,
            IClientService clientService,
            IParcelService parcelService,
            IUserService userService,
            IEmailService mailService,
            UserManager<ApplicationUser> userManager,
            IMapper mapper)
        {
            this.officeService = officeService;
            this.clientService = clientService;
            this.parcelService = parcelService;
            this.userService = userService;
            this.mailService = mailService;
            this.userManager = userManager;
            this.mapper = mapper;
        }

        public IActionResult AddParcel()
        {
            AddParcelInputModel model = new AddParcelInputModel();
            this.LoadAddParcelInputModel(model);

            return this.View(model);
        }

        [HttpPost]
        public async Task<IActionResult> AddParcel(AddParcelInputModel input)
        {
            if (this.ModelState.IsValid)
            {
                var user = this.userService.GetUserByClaimsPrincipal(this.User);

                (input.DeliveryPrice, input.ChargeType) = this.CalculateDeliveryPrice(input);

                input.SendingOffice = user.WorkOffice;
                input.CurrentOffice = user.WorkOffice;
                input.SendingEmployee = user;

                var newParcel = await this.parcelService.CreateAsync(input);

                await this.mailService.SendNewParcelEmailsAsync(newParcel.Id);

                this.ViewBag.isSuccess = true;
                this.ModelState.Clear();

                input = new AddParcelInputModel();
            }

            this.LoadAddParcelInputModel(input);
            return this.View(input);
        }

        public IActionResult DisposeParcel()
        {
            return this.View();
        }

        [HttpGet]
        [IgnoreAntiforgeryToken]
        public decimal CalculateDeliveryPrice(CalculateDeliveryPriceDto input)
        {
            var finalPrice = 5.20m;

            var volumeWeight = input.Height * input.Width * input.Length;

            // To decide if the charge is by dimensions or my weight
            finalPrice += (this.DecideChargeType(volumeWeight, input.Weight) == ParcelChargeType.Dimensions ? volumeWeight * 0.1m : input.Weight * 0.1m);

            // if cash on delivery is selected
            finalPrice += (input.HasCashOnDelivery && input.CashOnDeliveryPrice > 0 ? input.CashOnDeliveryPrice / 95.0m : 0);

            // if IsFragile is selected
            finalPrice *= (input.IsFragile ? 1.02m : 1);

            // if DontPaletize is selected
            finalPrice *= (input.DontPaletize ? 1.04m : 1);

            // if there are more than 1 part
            finalPrice += (input.NumberOfParts > 1 ? finalPrice * input.NumberOfParts * 0.03m : 0);

            return finalPrice;
        }

        [HttpGet]
        [IgnoreAntiforgeryToken]
        public ClientDetailsDto GetClientDetailsById(int id)
        {
            var client = this.clientService.GetClientById(id);
            return this.mapper.Map<ClientDetailsDto>(client);
        }

        [HttpPost]
        [IgnoreAntiforgeryToken]
        public async Task<Result> EditClientDetails(ClientDetailsDto clientDetails)
        {
            var clientModel = this.mapper.Map<Client>(clientDetails);
            return await this.clientService.EditClientInfoAsync(clientModel);
        }

        private void LoadAddParcelInputModel(AddParcelInputModel input)
        {
            var currUser = this.userService.GetUserById(this.User.FindFirst(ClaimTypes.NameIdentifier).Value);
            var allClients = this.clientService.GetAllClientsAsKeyValuePairs();

            input.SenderInputModel.AllClients = allClients;
            input.RecipentInputModel.AllClients = allClients;

            input.AllOffices = this.officeService.GetAllOfficesAndSortingCentersWithoutCurrOneAsKeyValuePairs(0);
            input.CurrOfficeAsString = this.officeService.GetOfficeAsStringById(currUser.WorkOfficeId);
        }

        private (decimal, ParcelChargeType) CalculateDeliveryPrice(AddParcelInputModel input)
        {
            var heightAsDecimal = input.Height == null ? 1m : decimal.Parse(input.Height?.Replace('.', ','));
            var lengthAsDecimal = input.Length == null ? 1m : decimal.Parse(input.Length?.Replace('.', ','));
            var widthAsDecimal = input.Width == null ? 1m : decimal.Parse(input.Width?.Replace('.', ','));
            var cashOnDeliverAsDecimal = input.CashOnDeliveryPrice == null ? 0 : decimal.Parse(input.CashOnDeliveryPrice?.Replace('.', ','));
            var weightAsDecimal = input.Weight == null ? 1m : decimal.Parse(input.Weight?.Replace('.', ','));

            var calculatePriceDto = this.mapper.Map<CalculateDeliveryPriceDto>(input);
            calculatePriceDto.Height = heightAsDecimal;
            calculatePriceDto.Length = lengthAsDecimal;
            calculatePriceDto.Width = widthAsDecimal;
            calculatePriceDto.CashOnDeliveryPrice = cashOnDeliverAsDecimal;
            calculatePriceDto.Weight = weightAsDecimal;

            var finalPrice = this.CalculateDeliveryPrice(calculatePriceDto);

            var volume = heightAsDecimal * lengthAsDecimal * widthAsDecimal;

            return (finalPrice, this.DecideChargeType(volume, weightAsDecimal));
        }

        private ParcelChargeType DecideChargeType(decimal volumeWeight, decimal weight)
        {
            if (volumeWeight > weight / 2)
            {
                return ParcelChargeType.Dimensions;
            }
            else
            {
                return ParcelChargeType.Weight;
            }
        }
    }
}

Web/FinalPoint.Web/Controllers/AdministrationController.cs
namespace FinalPoint.Web.Controllers
{
    using System.Linq;
    using System.Security.Claims;
    using System.Threading.Tasks;
    using AutoMapper;
    using FinalPoint.Common;
    using FinalPoint.Data.Models;
    using FinalPoint.Web.Business.Interfaces;
    using FinalPoint.Web.ViewModels;
    using FinalPoint.Web.ViewModels.Administration;
    using FinalPoint.Web.ViewModels.DTOs;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Identity;
    using Microsoft.AspNetCore.Mvc;

    [Authorize(Roles = GlobalConstants.AdministratorRoleName + ", " + GlobalConstants.OwnerRoleName + ", " + GlobalConstants.OfficeOwnerRoleName)]
    public class AdministrationController : BaseController
    {
        private readonly IOfficeService officeService;
        private readonly ICityService cityService;
        private readonly IUserService userService;
        private readonly IThemeService themeService;

        public AdministrationController(
            IOfficeService officeService,
            ICityService cityService,
            IUserService userService,
            IThemeService themeService)
        {
            this.officeService = officeService;
            this.cityService = cityService;
            this.userService = userService;
            this.themeService = themeService;
        }

        public IActionResult Index(Result model)
        {
            return this.View(model);
        }

        public IActionResult FireEmployee()
        {
            FireEmployeeInputModel model = new FireEmployeeInputModel();

            this.LoadFireEmployeeViewModel(model);

            return this.View(model);
        }

        [HttpPost]
        public async Task<IActionResult> FireEmployee(FireEmployeeInputModel input)
        {
            if (this.ModelState.IsValid)
            {
                var removedUser = await this.userService
                        .RemoveUserAsync(input.EmployeeToFire);

                if (removedUser != null)
                {
                    input.ResultMessage = $"Служител - {removedUser.FirstName} {removedUser.MiddleName} {removedUser.LastName} - {removedUser.PersonalId} - беше уволнен успешно.";
                }
            }

            this.LoadFireEmployeeViewModel(input);

            return this.View(input);
        }

        public IActionResult AddOffice()
        {
            AddOfficeInputModel model = new AddOfficeInputModel();
            this.LoadAddOfficeViewModel(model);
            return this.View(model);
        }

        [HttpPost]
        public async Task<IActionResult> AddOffice(AddOfficeInputModel input)
        {
            if (this.ModelState.IsValid)
            {
                await this.officeService.CreateAsync(input);

                var result = new Result() { Success = true, Message = input.ResultMessage = $"Офис {input.Name} беше регистриран успешно!" };

                return this.RedirectToAction("Index", result);
            }

            this.LoadAddOfficeViewModel(input);
            return this.View(input);
        }

        public IActionResult RemoveOffice()
        {
            RemoveOfficeInputModel model = new RemoveOfficeInputModel();
            model.AvailableOfficesToRemove = this.officeService.GetOnlyAllOfficesAsKeyValueParis();
            return this.View(model);
        }

        [HttpPost]
        public async Task<IActionResult> RemoveOffice(RemoveOfficeInputModel input)
        {
            if (this.ModelState.IsValid)
            {
                var removedOffice = await this.officeService.RemoveAsync(input.OfficeToRemove);
                input.ResultMessage = $"Офис - {removedOffice.Name} - {removedOffice.PostCode} - беше прекратен успешно.";
            }

            input.AvailableOfficesToRemove = this.officeService.GetOnlyAllOfficesAsKeyValueParis();

            return this.View(input);
        }

        public IActionResult Settings()
        {
            var model = this.CreateSettingsViewModel();

            return this.View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Settings(SettingsInputModel input)
        {
            Result vm = null;

            if (this.ModelState.IsValid)
            {
                var officeId = this.userService.GetUserOfficeByClaimsPrincipal(this.User);

                var result = await this.officeService.ChangeOfficeThemeAsync(officeId, input.SelectedThemeId);

                if (result)
                {
                    vm = new Result() { Success = true, Message = "Темата беше зададена успешно." };
                }
            }

            if (vm == null)
            {
                vm = new Result() { Success = false, Message = GlobalErrorMessages.WeHadAProblemPleaseLogInAgain };
            }

            return this.RedirectToAction("Index", vm);
        }

        private SettingsInputModel CreateSettingsViewModel()
        {
            var model = new SettingsInputModel();
            model.AvailableThemes = this.themeService
                    .GetAllThemesAsKeyValuePair()
                    .ToList();

            return model;
        }

        private void LoadAddOfficeViewModel(AddOfficeInputModel input)
        {
            input.CitiesItems = this.cityService.GetAllCitiesAsKeyValuePairs();
            input.SortingCentersItems = this.officeService.GetAllSortingCentersAsKeyValuePairs();
            input.AllUsers = this.userService.GetAllUsersAsKeyValuePair();
        }

        private void LoadFireEmployeeViewModel(FireEmployeeInputModel input)
        {
            var currUserId = this.User
                            .FindFirst(ClaimTypes.NameIdentifier)
                            .Value;

            input.AvailableEmployeesToDelete = this.userService.GetAllUsersWithoutCurrentAsKeyValuePair(currUserId);
        }
    }
}

Web/FinalPoint.Web/Controllers/HomeController.cs
namespace FinalPoint.Web.Controllers
{
    using System.Diagnostics;
    using System.Linq;
    using System.Security.Claims;
    using System.Threading.Tasks;

    using FinalPoint.Common;
    using FinalPoint.Data.Models;
    using FinalPoint.Web.Business.Interfaces;
    using FinalPoint.Web.ViewModels;
    using FinalPoint.Web.ViewModels.Home;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Identity;
    using Microsoft.AspNetCore.Mvc;

    public class HomeController : BaseController
    {
        private readonly IUserService userService;
        private readonly IOfficeService officeService;
        private readonly UserManager<ApplicationUser> userManager;
        private readonly IThemeService themeService;

        public HomeController(
            IUserService userService,
            IOfficeService officeService,
            UserManager<ApplicationUser> userManager,
            IThemeService themeService)
        {
            this.userService = userService;
            this.officeService = officeService;
            this.userManager = userManager;
            this.themeService = themeService;
        }

        public IActionResult Index()
        {
            var model = this.LoadIndexViewModel();
            return this.View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Index(HomeIndexInputModel input)
        {
            if (this.ModelState.IsValid)
            {
                var result = await this.userService
                    .SetUserNewWorkOfficeByUserIdAsync(this.User.FindFirstValue(ClaimTypes.NameIdentifier), input.OfficeId);

                if (result)
                {
                    this.themeService.UpdateThemeInHttpContext();
                }
            }

            input = this.LoadIndexViewModel();
            return this.View(input);
        }

        [AllowAnonymous]
        public IActionResult Assets()
        {
            var model = new LoginUsersAndOfficesShowViewModel();
            model.Users = this.userService.GetAllUsers();
            model.Offices = this.officeService.GetAllOfficesAsStringWithoutVirtual();
            return this.View(model);
        }

        private HomeIndexInputModel LoadIndexViewModel()
        {
            var model = new HomeIndexInputModel();
            var user = this.userService.GetUserById(this.User.FindFirstValue(ClaimTypes.NameIdentifier));

            var isOwner = this.User.IsInRole(GlobalConstants.OwnerRoleName);
            var isAdministrator = this.User.IsInRole(GlobalConstants.AdministratorRoleName) || this.User.IsInRole(GlobalConstants.OfficeOwnerRoleName);
            var isFromVirtualOffice = user.WorkOfficeId == this.officeService.GetVirtualOffice().Id;

            model.ShowOfficeModules = !isOwner || !isFromVirtualOffice;
            model.ShowAdministratorModule = isOwner || isAdministrator;
            model.IsOwner = isOwner;
            model.FullName = this.userManager.GetUserAsync(this.User)?.Result?.FullName;
            model.CurrentWorkOfficeId = user.WorkOfficeId;
            model.AvailableOffices = this.officeService.GetAllOfficesAndSortingCentersAsKeyValuePairs().OrderByDescending(x => x.Key == user.WorkOfficeId.ToString());

            return model;
        }
    }
}

Web/FinalPoint.Web/Controllers/SearchController.cs
namespace FinalPoint.Web.Controllers
{
    using FinalPoint.Web.Business.Interfaces;
    using Microsoft.AspNetCore.Mvc;

    public class SearchController : BaseController
    {
        private readonly IProtocolService protocolService;
        private readonly IUserService userService;

        public SearchController(
            IProtocolService protocolService,
            IUserService userService)
        {
            this.protocolService = protocolService;
            this.userService = userService;
        }

        public IActionResult Index()
        {
            return this.View();
        }

        public IActionResult Parcel()
        {
            return this.View();
        }

        public IActionResult Protocol()
        {
            var user = this.userService.GetUserByClaimsPrincipal(this.User);
            var protocols = this.protocolService.GetLocalProtocolsByOfficeId(user.WorkOfficeId);
            return this.View(protocols);
        }
    }
}

Web/FinalPoint.Web/Views/Home/Assets.cshtml
@using FinalPoint.Web.ViewModels.Home
@model LoginUsersAndOfficesShowViewModel
@{
    ViewData["Title"] = "Налични потребители и офиси";
    ViewData["Breadcrumb"] = new List<KeyValuePair<string, string>>() {
        new KeyValuePair<string, string>("Начало", "/"),
        };
}

<h1 class="text-center text-secondary mb-4">@ViewData["Title"]</h1>
<hr class="" />

<h2 class="text-center">Потребители: <p class="h6">(Паролата за всеки потребител е N111111)</p></h2>

<table class="table table-striped table-hover ">
    @foreach (var user in Model.Users)
    {
        <tr>
            <td>@user</td>
        </tr>
    }
</table>


<h2 class="text-center">Офиси:</h2>

<table class="table table-striped table-hover ">
    @foreach (var office in Model.Offices)
    {
        <tr>
            <td>@office</td>
        </tr>
    }
</table>

Web/FinalPoint.Web/Views/Home/Index.cshtml
@using FinalPoint.Web.ViewModels.Home
@{
    ViewData["Title"] = "Начало";
    var allOffices = Model.AvailableOffices?.Select(x => new SelectListItem(x.Value, x.Key));
}

@model HomeIndexInputModel

<div class="container-fluid">
    <div class="row">
        <div class="col-md-12">
            <h1 class="text-center text-secondary mb-4">Добре дошли, @Model.FullName</h1>
            <hr />

            @if (Model.IsOwner)
            {
                <div class="text-center mb-4">
                    <form method="post" class="col-md-6 m-auto text-align-center">
                        <label asp-for="OfficeId"></label>
                        <div class="form-group d-flex">
                            <select id="officeSelect" asp-for="OfficeId" asp-items="allOffices" data-live-search="true" class="selectpicker form-control col-md-8">
                            </select>

                            <button type="submit" id="delBtn" class="btn btn-primary col-md-3 animate__animated animate__backInRight animate__faster">Напред ></button>
                        </div>

                        <span asp-validation-for="OfficeId" class="text-danger"></span>
                    </form>
                </div>
            }

            @if (Model.ShowOfficeModules)
            {
                <div class="row offset-md-2">
                    <div class="col-md-5">
                        <a asp-controller="AddDispose" asp-action="AddParcel">
                            <div class="card border-left-info shadow mb-3" style="width: 18rem;">
                                <div class="card-body">
                                    <h5 class="card-title text-secondary hover-underline-animation">Приемане на пратка</h5>
                                </div>
                            </div>
                        </a>
                    </div>

                    <div class="col-md-5">
                        <a asp-controller="AddDispose" asp-action="DisposeParcel">
                            <div class="card border-left-info shadow mb-3" style="width: 18rem;">
                                <div class="card-body">
                                    <h5 class="card-title text-secondary hover-underline-animation">Издаване на пратка</h5>
                                </div>
                            </div>
                        </a>
                    </div>
                </div>

            <div class="row offset-md-2">
                <div class="col-md-5">
                    <a asp-controller="Load">
                        <div class="card border-left-info shadow mb-3" style="width: 18rem;">
                            <div class="card-body">
                                <h5 class="card-title text-secondary hover-underline-animation">Товарене</h5>
                            </div>
                        </div>
                    </a>
                </div>

                <div class="col-md-5">
                    <a asp-controller="Unload">
                        <div class="card border-left-info shadow mb-3" style="width: 18rem;">
                            <div class="card-body">
                                <h5 class="card-title text-secondary hover-underline-animation">Разтоварване</h5>
                            </div>
                        </div>
                    </a>
                </div>
            </div>
                }
            <div class="row offset-md-2">
                <div class="col-md-5">
                    <a asp-controller="Search">
                        <div class="card border-left-info shadow mb-3" style="width: 18rem;">
                            <div class="card-body">
                                <h5 class="card-title text-secondary hover-underline-animation">Търсене</h5>
                            </div>
                        </div>
                    </a>
                </div>

                @if (Model.ShowAdministratorModule)
                {
                    <div class="col-md-5">
                        <a asp-controller="Administration">
                            <div class="card border-left-info shadow mb-3" style="width: 18rem;">
                                <div class="card-body">
                                    <h5 class="card-title text-secondary hover-underline-animation">Администрация</h5>
                                </div>
                            </div>
                        </a>
                    </div>
                }
            </div>
        </div>
    </div>
</div>
<style>
</style>